title: Nicolás Salazar Beltrán # your name (or website title) here
logo: "/images/hs_li.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data scientist with a solid background in programming and systems engineering.
  Have found in Data Science the right complement to contribute in different areas, leveraging my technical skills to derive insights, build predictive models, and support data-driven decisions in new high-tech projects.
  <br><br>
  Successfully completed the MIT Professional Education Applied Data Science Program with full marks.
  <br><br>
  Currently based in Barcelona.
  <br><br>
  <a href="https://www.linkedin.com/in/nicolas-salbe/">¡Hola! LinkedIn</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-JYP3QSFMFD # your Google Analytics tracking ID here
